-- @glitzy/core-content — C0006 LegalDocument (DATA_MODEL C-16·LOCATION_LEGAL_PLAN v1.0)
-- Precondition: D0010 instance · C0004 content_publication_status enum · C0005 risk_level enum

-- LL-SCHEMA-01: documentType enum (DATA_MODEL C-16 SoT 7종)
CREATE TYPE legal_document_type AS ENUM (
  'privacy', 'terms', 'non-covered', 'refund', 'complaint', 'cookie', 'other'
);

CREATE TABLE legal_document (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  instance_id UUID NOT NULL REFERENCES instance(id) ON DELETE CASCADE,
  slug TEXT NOT NULL,
  document_type legal_document_type NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  auto_generated BOOLEAN NOT NULL DEFAULT true,
  template_version TEXT,
  -- LLC-11 patch (LL-ACTION-07): default 시점 = 'Asia/Seoul' 의 오늘. server new Date() 사용 금지.
  -- form/action 이 항상 값을 넣지만 (zod required) DB default 는 직접 SQL 경로 안전망.
  effective_date DATE NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul')::date),
  last_revised_date DATE,
  contact_person TEXT,
  contact_email TEXT,
  status content_publication_status NOT NULL DEFAULT 'draft',
  risk_level risk_level NOT NULL DEFAULT 'Low',
  published_at TIMESTAMPTZ,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT legal_document_slug_regex CHECK (slug ~ '^[a-z0-9][a-z0-9-]{2,63}$'),
  CONSTRAINT legal_document_title_length CHECK (length(title) BETWEEN 1 AND 100),
  CONSTRAINT legal_document_body_length CHECK (length(body) BETWEEN 1 AND 200000),
  CONSTRAINT legal_document_email_regex CHECK (
    contact_email IS NULL OR contact_email ~ '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
  ),
  -- LL-SCHEMA-05 + cycle1 LL-22: autoGenerated=true 시 templateVersion 필수
  CONSTRAINT legal_document_template_version_format CHECK (
    template_version IS NULL OR template_version ~ '^[a-z0-9-]+@[0-9]+\.[0-9]+\.[0-9]+$'
  ),
  CONSTRAINT legal_document_auto_generated_template_ver CHECK (
    (auto_generated = false) OR (template_version IS NOT NULL)
  ),
  -- LL-SCHEMA-03 + cycle1 LL-03·LL-19: skeleton 단계 status='draft' 만
  CONSTRAINT legal_document_status_skeleton_limit CHECK (status = 'draft'),
  -- LL-SCHEMA-04: 발행 자체 차단
  CONSTRAINT legal_document_published_at_null CHECK (published_at IS NULL),
  -- LL-SCHEMA-06 + cycle1 LL-12: risk_level 'Low' 만
  CONSTRAINT legal_document_risk_level_skeleton_limit CHECK (risk_level = 'Low'),
  CONSTRAINT legal_document_instance_slug_unique UNIQUE (instance_id, slug),
  CONSTRAINT legal_document_instance_id_unique UNIQUE (instance_id, id)
);

-- LL-SCHEMA-02 + cycle1 LL-08·09: closed 5종 partial UNIQUE (cookie/other 미강제 — LL-DEFER-12)
CREATE UNIQUE INDEX legal_document_instance_5type_unique
  ON legal_document (instance_id, document_type)
  WHERE document_type IN ('privacy', 'terms', 'non-covered', 'refund', 'complaint');

CREATE INDEX legal_document_instance_idx ON legal_document (instance_id);

ALTER TABLE legal_document ENABLE ROW LEVEL SECURITY;
ALTER TABLE legal_document FORCE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON legal_document
  FOR ALL TO app_tenant_user
  USING (instance_id = NULLIF(current_setting('app.current_instance_id', true), '')::uuid)
  WITH CHECK (instance_id = NULLIF(current_setting('app.current_instance_id', true), '')::uuid);

GRANT SELECT, INSERT, UPDATE, DELETE ON legal_document TO app_tenant_user;
